### ISSUE TITLE
Want to run SimpleWebSocketServer with Apache 2.2 instead of Http Basic Server of python 

### ISSUE THREAD

**Issue by bhagavan** [dpallot/simple-websocket-server#11]
Hi Opiate,

 I deployed SWS in remote machine where already Apache web server running in 443 port, want to run SWS on TLS connections with existing certificates, is there any way to do 

Thank you

**Comment by dpallot** [comment]
You should be able to just reference your existing cert through the keyfile and certfile variables in the SimpleSSLWebSocketServer init function.
