### ISSUE TITLE
Run with Python3

### ISSUE THREAD

**Issue by tecpal** [dpallot/simple-websocket-server#12]
I tried to convert the code to Python3 and try running. Having some errors. Can you please implement the same code for Python3

**Comment by opiate** [comment]
I will have a look at porting.

**Comment by opiate** [comment]
Creating an asyncio version for python 3

**Comment by Cottin** [comment]
+1

**Comment by dpallot** [comment]
I've spawned off a new project called async-websockets (https://github.com/dpallot/async-websockets) that uses python3 co-routines. It's faster, more efficient and much easier to use.

**Comment by tecpal** [comment]
Thanks. I will try and give you feedback.

**Comment by tecpal** [comment]
Thanks a lot. It works great and I appreciate the great work you did using asyncio in python3.

**Comment by dpallot** [comment]
Found a bit of time so I added support for python3. 
Regards
