### ISSUE TITLE
Integration with web.py

### ISSUE THREAD

**Issue by aartek** [dpallot/simple-websocket-server#15]
Hello I'm writing simple app with `web.py`, and I'd like to integrate it with your lib.
However I have problem with combining it together.
Because `serveforever()` method runs`while True` loop, I cannot run webpy's `app.run()` method, which is needed to start the server. Without `app.run()` I cannot open connection from browser (my index page is not static - it is rendered by `web py`), so serveforever is still waiting.
If I change the order and first I call `app.run()`, then I cannot call `serveforever()`.

Do you have any idea how to solve this problem?
I've tried to do something with threads but I cannot share "sendMessage" method between them.

Code draft http://pastebin.com/Hbq4DiEy

**Comment by dpallot** [comment]
Calling serverforever() in a separate thread should work. You could always use the multiprocess library to spawn a new process if required.
