### ISSUE TITLE
Unable to connect to ws server

### ISSUE THREAD

**Issue by anandumdas** [dpallot/simple-websocket-server#22]
I am fairly new to programming and python.  I did as explained in the homepage.

1. Installed using the command `sudo pip install git+https://github.com/dpallot/simple-websocket-server.git`
2. Downloaded the files  __init__.py ,SimpleHTTPSServer.py,websocket.html, SimpleExampleServer.py,  SimpleWebSocketServer.py
3. Right click and opened websocket.html with chrome. 

When I try to press the connect button, I get error

    error: undefined
    disconnected

What could be the possible issue? I did some mistakes in the procedures?

**Comment by Steindi01** [comment]
Please make sure you started the server correctly with either:
python <PATH_TO_FILE>/SimpleExampleServer.py --example echo
or
python <PATH_TO_FILE>/SimpleExampleServer.py --example chat
Reopen or refresh the websocket.html page afterwards.
Am 18.09.2015 11:38 schrieb anandumdas <notifications@github.com>:I am fairly new to programming and python.  I did as explained in the homepage.

Installed using the command sudo pip install git+https://github.com/dpallot/simple-websocket-server.git
Downloaded the files  init.py ,SimpleHTTPSServer.py,websocket.html, SimpleExampleServer.py,  SimpleWebSocketServer.pyRight click and opened websocket.html with chrome. 

When I try to press the connect button, I get error

error: undefined
disconnected


What could be the possible issue? I did some mistakes in the procedures?

**Comment by anandumdas** [comment]
There was an error connecting to server from my side. Closing the issue.
