### ISSUE TITLE
Run Web Socket in a separate thread

### ISSUE THREAD

**Issue by martinsik** [dpallot/simple-websocket-server#23]
Hi, I'm trying to run Web Socket server in another thread while being able to send messages to clients:

```python
clients = []
class SimpleChat(WebSocket):

    def handleMessage(self):
       for client in clients:
          if client != self:
             client.sendMessage(self.address[0] + ' - ' + self.data)

    def handleConnected(self):
       print self.address, 'connected'
       for client in clients:
          client.sendMessage(self.address[0] + u' - connected')
       clients.append(self)

    def handleClose(self):
       clients.remove(self)
       print self.address, 'closed'
       for client in clients:
          client.sendMessage(self.address[0] + u' - disconnected')

def run_server():
    server = SimpleWebSocketServer.SimpleWebSocketServer('', 9000, SimpleChat)
    server.serveforever()

t = threading.Thread(target=run_server)
t.start()

while True:
    for client in clients:
        client.sendMessage('ping')
    time.sleep(1)
```

It doesn't seem to be sending any messages. Is it because the loop is blocking the main thread? Is there any better way to do it?

**Comment by dpallot** [comment]
Specify the ```setInterval``` parameter on the init function of SimpleWebSocketServer (maybe 1 sec). If its not set then the blocking select will not be waiting on the descriptor unless the endpoint sends some data. Note that the above code is not thread safe with the current implementation.

**Comment by martinsik** [comment]
Thanks, `selectInterval` helped.
Can you give me just brief info why is this happening? Is it because the `while True` loop blocks the main thread instead of `SimpleWebSocketServer` so messages are queued but never actually sent?

**Comment by dylancaponi** [comment]
What exactly is selectInterval doing?  Why is this not thread safe?
