### ISSUE TITLE
error code when closing the socket because of an error

### ISSUE THREAD

**Issue by lrusnac** [dpallot/simple-websocket-server#31]
Hi, I have a simple echo example with a counter for total number of messages the server has received:

```
from SimpleWebSocketServer import SimpleWebSocketServer, WebSocket

count = 0
class SimpleEcho(WebSocket):

    def handleMessage(self):
        # echo message back to client
        print 'received ', self.data, ' from ', self.address
        #count = count+1
        msg = self.data[::-1] + str(count)
        self.sendMessage(msg)
        count = count + 1

    def handleConnected(self):
        print self.address, 'connected'

    def handleClose(self):
        print self.address, 'closed'

server = SimpleWebSocketServer('', 8080, SimpleEcho)
server.serveforever()
```

then I have a simple javascript connection:

```
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8" />
		<title>Sample of websocket with python</title>
		<script src="jquery-2.1.4.min.js"></script>
		<script>
      $(function() {
        var ws = new WebSocket("ws://localhost:8080");
        ws.onmessage = function(e) {
		  $('<li>').text("received: " + e.data).appendTo($ul);
        };

        var $ul = $('#msg-list');
        $('#sendBtn').click(function(){
          var data = $('#name').val();
          ws.send(data);
          $('<li>').text("send: " + data).appendTo($ul);
        });
      });
		</script>
	</head>
	<body>
			<input id="name" type="text" />
			<input type="button" id="sendBtn" value="send"></input>
      <ul id="msg-list"></ul>
	</body>
</html>
```

this fails by closing the socket:
```
$ python main.py
('127.0.0.1', 59238) connected
received  sfdfsdf  from  ('127.0.0.1', 59238)
('127.0.0.1', 59238) closed
```

it works fine if I don't change the value of count in the socket class, but I want to understand where is the problem and tried to print a lot of different fields of the ws object in the ``handleClose`` method but I can't find any error or debugging message.

**Comment by dpallot** [comment]
The problem is with your count variable. If you want to use it as a global variable then you need to add a global reference to it in your handleMessage. So at the top of your function add: global count

**Comment by lrusnac** [comment]
I know that the error is in count as I mentioned in the issue, but my point was if there is a way of debugging to see that that's the error. Immagine I have a quite big logic there and the connection closes without giving me back any error, try to find that you are missing a `global` or `self` or something else.

So again, is there a way to get an error message when the server closes the connection to the client due to an error?

**Comment by dpallot** [comment]
Nothing in the implementation. Maybe add a log message when handleMessage throws an exception. Happy to merge it in.
