### ISSUE TITLE
Is there any example that the server push directly to the clients?

### ISSUE THREAD

**Issue by litterbear** [dpallot/simple-websocket-server#32]
In the examples, I found all the `sendMessage` calls were triggered by  `handleMessage` or `handleConnected`. 
I want to call sendMessage at any time I want.  Such as everytime I read a line from stdin.

So I wrote such script, however it didn't work.

``` python
#!/usr/bin/env python

import threading
from SimpleWebSocketServer import SimpleWebSocketServer, WebSocket

conns = []

class SimpleStdinPub(WebSocket):

    def handleConnected(self):
        conns.append(self)

    def handleClose(self):
        conns.remove(self)


server = SimpleWebSocketServer('0.0.0.0', 9000, SimpleStdinPub)


def read_stdin():
    while True:
        line = raw_input()
        for conn in conns:
            conn.sendMessage(line)

if __name__ == '__main__':
    t = threading.Thread(target=server.serveforever)
    t.setDaemon(True)
    t.start()
    read_stdin()
```

I tried all kinds of ways. It seems it doesn't work when I call `sendMessage` in another thread.
But I can't figure out any way I can call sendMessage in the same thread.

Could anyone tell me how could I achieve this?
Thanks :)

**Comment by litterbear** [comment]
I think many users will like this example https://github.com/crossbario/autobahn-python/tree/master/examples/twisted/websocket/broadcast

If we can replace tick function with a callback everytime stdin returned, it will better!

**Comment by dpallot** [comment]
As the implementation is non-threaded you need to set the setInterval on the constructor to some value so it will poll if there is data to send i.e. 0.1. 
Seems like a few people are having this problem so I added a default value.
