### ISSUE TITLE
can't install properly with Python3

### ISSUE THREAD

**Issue by alexorex** [dpallot/simple-websocket-server#33]
Having installed with pip3 using either of "setup.py" and "git+https" methods, can't execute example server.
First error is "cannot import name 'WebSocket'".
If import from the SimpleWebSocketServer dir directly, works fine.
Pip for py2 works normally.

**Comment by DennisSchulmeister** [comment]
I had the same issue. Python3 is more strict about relative imports. __init__.py should be changed to

`from .SimpleWebSocketServer import *`

(Notice the dot)``

**Comment by dpallot** [comment]
Thanks for resolving the issue.
