### ISSUE TITLE
Server swallows exceptions

### ISSUE THREAD

**Issue by scribu** [dpallot/simple-websocket-server#35]
I appreciate the easy of use of this library, so thanks for that!

What I don't appreciate is that it silently eats exceptions that occur in any method of a child class of `WebSocket`.

I tried to add logging, as suggested in #31, but there are too many `except: pass` everywhere and I don't know which are just catching `KeyError`s and which should have logging.

**Comment by dpallot** [comment]
Yeah its a fair critisim. I have cleaned up the exceptions in the select loop. Feel free to add the logging you think is correct and we can look at merging the changes.
