### ISSUE TITLE
Failed with error: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused"

### ISSUE THREAD

**Issue by sashakid** [dpallot/simple-websocket-server#38]
Hi, I'm trying to connect from my sample iOS app using URL: `"ws://localhost:8000"` and getting error: `"Connection refused"` . Am I doing something wrong and your server is not suited for any other platform? Or is it the problem on my side? Thanks :-)

**Comment by dpallot** [comment]
Hi sashakid,
I am unable to replicate this problem. It sounds like a very platform specific problem, do you have any firewalls etc blocking this port?
I'll close for now but if you have any more info I will open it again.
