### ISSUE TITLE
How to stop server properly?

### ISSUE THREAD

**Issue by darenju** [dpallot/simple-websocket-server#40]
Hello,

I am using this web socket server in a Sublime Text plugin, and I need to stop the server properly once it is not used anymore.

The server is used in a thread, that I can access from anywhere in my plugin. How do I tell it to stop listening?

When I use `server.close()`, I get this error:

```
  File "server.py", line 679, in <module>
    server.serveforever()
  File "server.py", line 612, in serveforever
    rList, wList, xList = select(self.listeners, writers, self.listeners, self.selectInterval)
```

The same thing happens when I just make a simple file and Ctrl+C it from the command line.

What did I do wrong?

**Comment by denghui1010** [comment]
+1

**Comment by dpallot** [comment]
You will get that error when select is blocking or being called a the time `close` is called which is normal. If you want to ignore the exception just put an exception handler around `serveforever()` and then take no action.
