### ISSUE TITLE
how to run example

### ISSUE THREAD

**Issue by evbo** [dpallot/simple-websocket-server#42]
When running `python SimpleExampleServer.py --example echo` I am not able to see received responses via:

`socat - TCP:localhost:8000`

There is simply no output after trying to connect to the websocket. How should this example websocket server be communicated with?

I know I am able to setup a websocket server because other tools work, such as wscat:

```
sudo npm install -g wscat
wscat -l 8000 -p 13
listening on port 8000 (press CTRL+C to quit)
client connected
< {"text":"hello"}
```

Also, In order to run the example after installing using pip, i must first cd:

`cd /Library/Python/2.7/site-packages/SimpleWebSocketServer`

otherwise I get:

> python SimpleExampleServer.py --example echo
> python: can't open file 'SimpleExampleServer.py': [Errno 2] No such file or directory

Should the docs be updated to include cd'ing to that directory first?

**Comment by dpallot** [comment]
Hi Evbo,
`socat` does not inherently support the websocket protocol and as you correctly found out `wscat` does. However I think wscat just echos your input so running the echo example against wscat should work fine but will not work for anything else.

In regards to communication with the websocket server, you can use any websocket client you like, just do a quick google or search on github and you will find many. You can also open the `websocket.html` file which is a browser based interface that will work with both examples.

In regards to installation, there is a `setup.py` that you can use which will do the installation for you. The best way to go about this is to use a virtual environment to keep your program separate from your system. 

>     virtualenv example
>     source example/bin/activate
>     cd SimpleWebSocketServer
>     python setup.py install


Then you should be able to run the example.
