### ISSUE TITLE
New feature: Simple HTTP server with websocket support

### ISSUE THREAD

**Issue by aplicacionamedida** [dpallot/simple-websocket-server#44]
I think that it's not too difficult to create an HTTP server with websocket support. Maybe reusing some code of the python module SimpleHTTPServer and BaseHTTPServer is possible to do something quick.

With this new feature added it will be possible to create local web servers with websocket support for web desktop applications in Python.

**Comment by dpallot** [comment]
Good idea! Maybe something you want to contribute to?
