### ISSUE TITLE
ValueError: filedescriptor out of range in select()

### ISSUE THREAD

**Issue by danielfaust** [dpallot/simple-websocket-server#46]
This is the second time I'm getting the exception `ValueError: filedescriptor out of range in select()`.

The server is running inside a Docker container under Alpine Linux 3.4. It has been running for six weeks without a restart with about three continuous connections during the entire time that were publishing data during the entire time, about 1x100byte message per 5 seconds. Not much disconnect/reconnect going on except for about 5 subscribers a day for a period of about one minute each.

```
Traceback (most recent call last):
  File "websocket.py", line 62, in <module>
    server.serveforever()
  File "/usr/lib/python2.7/site-packages/SimpleWebSocketServer/SimpleWebSocketServer.py", line 609, in serveforever
    rList, wList, xList = select(self.listeners, writers, self.listeners, self.selectInterval)
ValueError: filedescriptor out of range in select()
```

Is this an OS thing or could it be related to the server?

**Comment by dpallot** [comment]
Are you clients disconnecting properly i.e. are you getting the `handleClose` callback?
Also check your descriptor `ulimit` thats it not too low.

**Comment by coesa** [comment]
Any other open files in your process before you start the server can also add up and go over the 1024 limit for select, I ran into this recently. See https://mail.python.org/pipermail/python-list/2009-March/529177.html

Work-around was to always start the server first so it can have its one connection with a low file descriptor number, and then open other files.

**Comment by danielfaust** [comment]
Thanks. In my case it turned out to be a hardware issue, faulty RAM. It was very slowly corrupting the entire system and the error that made me submit this issue that was a side-effect of that.
