### ISSUE TITLE
Messages grouped into 100ms intervals

### ISSUE THREAD

**Issue by adammhaile** [dpallot/simple-websocket-server#49]
I'm using this to send image frame data of variable size at framerates up to 60fps. However, I've noticed in the packet timings, both in Chrome and Wireshark, that everything comes in as groupings about every 100ms. For example, if pushing packets at 30 per second, I usual will get timing such as: 102, 103, 103, 203, 204, 205, 302, 302, 303 where each of those numbers are the milliseconds portion of the timestamp shown in Chrome or Wireshark.  If I run at 60fps then I will get around 5-6 packets grouped together. 

I've added debug outputs in my [WebSocket ](https://github.com/ManiacalLabs/BiblioPixel/blob/new_vis/bibliopixel/drivers/webvis/__init__.py#L17)class when sending and it does not show the sends happening this way, as the timestamps are all nicely spread apart. 

I thought at first that maybe it was simply on the receiving end as shown by the network timings in Chrome, but Wireshark seems to prove this incorrect. In Wireshark I can see the groupings which suggest that although sendMessage() happens in a timely manner that the actual packets don't make it to the network right as they are sent. Note: this is all happening on localhost.

Also, this is occurring on Windows 10 and Fedora 24 in Chrome 56. 

Any thoughts on what might be the cause of this?

**Comment by dpallot** [comment]
What is happening is that the send is occurring in the select loop which delays your send. What I can do is create a separate send function or a flag to send data immediately. This should help you out with your timing issues.  I will think about the best approach and let you know.

**Comment by dpallot** [comment]
Thats because the send happens in the context of the select loop. To increase the loop cadence change selectInterval on the SimpleWebSocketServer or SimpleSSLWebSocketServer constructor to something like 0.001 (1ms) or whatever suits your application.

**Comment by adammhaile** [comment]
Gotcha. 1ms works fine. Maybe make it so if you set selectInterval to None
or 0 then it just runs without select?

**Comment by belm0** [comment]
I was caught by this as well.

In my use case, nothing may be inbound as far as new connections or messages for long periods, and I still need message output to be timely.  Furthermore there are cases where there is nothing inbound or outbound for long periods and I need the server to take 0% CPU.  So using a fast interval like 1 ms doesn't work because it causes high CPU use.

I saw a thread (https://stackoverflow.com/a/2162188) about `select()` working with multiprocessing.Queue, but the solution isn't valid for Windows.

**Comment by belm0** [comment]
There is a cross-platform solution to make Queue pollable:  https://stackoverflow.com/a/38002212

The PollableQueue code is from *Python Cookbook*
https://web.archive.org/web/20141228035455/http://chimera.labs.oreilly.com/books/1230000000393/ch12.html

**Comment by dpallot** [comment]
Happy for people to put in a pull request.
