### ISSUE TITLE
handleClose triggered on client connect

### ISSUE THREAD

**Issue by trendal** [dpallot/simple-websocket-server#50]
Using the SSL SimpleChat class, I get a handleClose event on every client connect.  So it of course errors with:  `ValueError: list.remove(x): x not in list`  this error was mentioned in the issue listed by vusdo.

An easy work around is:
`   def handleClose(self):
      if self in clients:
         clients.remove(self)
`
but it still shouldn't be running handleClose when a client connects.  I have confirmed the connection is NOT being closed from the client (javascript).

**Comment by dpallot** [comment]
Handled in #52
