### ISSUE TITLE
Connection auto close when using secure websocket

### ISSUE THREAD

**Issue by Austaras** [dpallot/simple-websocket-server#62]
Auto close when payload size > 1253 bytes

**Comment by studio-indelebil** [comment]
Hi,

I have the exact same problem when using SSL & sending "large" messages, between 1KB and 2KB, not always the same, depending on... who knows ! 

The client receives a "close" event with error code=1006 and reason="".

On the server side, the connection is closed without any exception, like if the client closed by himself (handleClose callback called).

I found nothing on the web that would help...

Any ideas ?

Jeremie

**Comment by studio-indelebil** [comment]
or maybe some advices on how to get more info on the "close" event ?

**Comment by ninjatrench** [comment]
This happened to me when the Websocket connection (SSL) was open for long time without exchanging any data. I solved it by keeping the communication channel busy with simple Ping Pong.

**Comment by djgerbil** [comment]
I'm not sure if this is the same issue but I've managed to set up my server without SSL and it all works fine, but when I enable SSL the client can send a message to the server ok, but when the server sends a reply the socket is closed, no matter the size of the message/payload. There is no error message on either the client (Web browser) or the server.

Any help/pointers would be great, thanks.

**Comment by krisstakos** [comment]
Any solution to this problem?

**Comment by krisstakos** [comment]
> 
> 
> Any solution to this problem?

Nevermind I solved it, it was variable that overflows just before sending it
