### ISSUE TITLE
Release on PYPI

### ISSUE THREAD

**Issue by talwrii** [dpallot/simple-websocket-server#66]
As things stand, one cannot use this as a dependency in a python library (installed by pip) and have this installable by other people. Basically pip has decided to deprecate git dependencies (https://github.com/pypa/pip/issues/4187) and provided no work around.

The easy work around is to provide this on pypi. This adds a bunch of complexity / credential / moving parts.

**Comment by talwrii** [comment]
So I've released my own fork as a work around.

If you get around to doing it yourself ping me and I will delete my fork.

**Comment by dpallot** [comment]
`pip install SimpleWebSocketServer`
