### ISSUE TITLE
Can't connect more users

### ISSUE THREAD

**Issue by startsts** [dpallot/simple-websocket-server#69]
I have something like chat-socket (used chat example + ssl), currently with ~300 active users, problem happens every 1-2 hours. New users can't connect, but it doesnt disconnect already connected users although their messages also don't reach socket "handleMessage" method.  Before with few users it also was happening but not so frequently.
In log file I can see only lines like that:

('78.46.227.52', 51444) connected
('78.46.227.52', 51444) closed

How to investigate details of the issue?

**Comment by dpallot** [comment]
Looks like a limitation in the number if descriptors you can have open at a time. I would suggest increasing that number in your OS.

**Comment by uzlonewolf** [comment]
This is possibly the SSL do_handshake() hang mentioned in #13.  If so, see #110 for a fix.
