### ISSUE TITLE
Performance question.

### ISSUE THREAD

**Issue by bvelasquez** [dpallot/simple-websocket-server#70]
Hello.  I'm working on a game that uses your library.  I'm hitting a wall on the number of simultaneous users that can send/receive data.  If I send too many messages via the websocket, to too many clients, the connections and messages choke.  About 60 connections at 25-30 messages a second down per connection and 30 messages a second up for all connections.

Is there a bottleneck in the library that might cause this and possible solutions to increase the throughput?

Thank you.

**Comment by dpallot** [comment]
I never really put this together for maximum performance. It was just hack that I cleaned up so people can play with websockets in python. If people want to put some performance changes in I would be happy to look at it.
