### ISSUE TITLE
HTTP server gets opened with "import *"

### ISSUE THREAD

**Issue by The-Compiler** [dpallot/simple-websocket-server#73]
When doing `from SimpleWebSocketServer import *`, `SimpleHTTPSServer.py` is executed as well, which opens a HTTP server on localhost when imported.

The code in there should probably be [guarded by a main-clause](https://docs.python.org/3/library/__main__.html) to not do that, and `__all__` should be set properly for the package.

See https://www.reddit.com/r/vim/comments/86hnfk/if_you_have_used_or_are_using_vimghost_you_should/

**Comment by dpallot** [comment]
4a9defa176919142d4bf738d307fb77fea0a04ad

**Comment by The-Compiler** [comment]
More like d49f2e6aafc53f591e7f4547da4c7311b2058ebb :wink:
