### ISSUE TITLE
naive question : can I have multiple privkey.pem

### ISSUE THREAD

**Issue by manatlan** [dpallot/simple-websocket-server#75]
I want to run a WSS on two domains names (ex: aaa.com & bbb.com) ...
I've reach to do it for each ssl domain with the according privkey separatly ...
But I'd like to listen on the 2 domains (with the 2 privkey.pem) at the same time ?
is it possible ?

**Comment by uzlonewolf** [comment]
This is now possible with the custom SSL contexts added in #80 and a custom context with ctx.set_servername_callback().
