### ISSUE TITLE
Authorisation check

### ISSUE THREAD

**Issue by Jacobh2** [dpallot/simple-websocket-server#89]
What is the recommended way to check if a connected client is actually authorised to connect to the server when this is needed?

Right now I check the headers as the first thing I do in `handleConnected` and `handleMessage` methods and if it is not ok, I call `self.close()`. But that does not force-quit the connection, as the documentation for `close` say: 
```
Send Close frame to the client.
The underlying socket is only closed when the
client acknowledges the Close frame.
```

Is it possible to force-quit the connection? Can I check if the client that is about to connect is authorised in an earlier stage?

**Comment by dpallot** [comment]
Should be fine to just throw an exception and it will close the connection.
