### ISSUE TITLE
a realease on PyPi

### ISSUE THREAD

**Issue by kdschlosser** [dpallot/simple-websocket-server#90]
someone has gone and released this library on PyPi. they stripped out all of the copyright notices and added this library (tho it does not function.

I thought I would let you know as this could bring some issues to you when people post issues for it not working.

here is the link to the persons github repository. 

https://github.com/Pithikos/python-websocket-server

The issue I have with this is the stripped out copyright the github repository is not a fork of this repository. the person created a whole new repository
they also released it on PyPi as well as their repository having the same name "simple-websocket-server"

so now you are unable to release this on PyPi with that name if you wanted to.
that is really annoying. I am not sure where to go from here because there are no websocket server libraries that support SSL listed on PyPi except the one mentioned above.

**Comment by mcepl** [comment]
When this will be resolved I will gladly make openSUSE package.

**Comment by dpallot** [comment]
> https://github.com/pikhovkin/simple-websocket-server

Im happy to do it if you want to release that name?

**Comment by kdschlosser** [comment]
@dpallot 

technically speaking the name of the library is SimpleWebSocketServer not simple_websocket_server.

simple_websocket_server is the name of the github repo. the name of the library if the name of the folder that contains all of the files needed to run the library. which is under the directory name of SimpleWebSocketServer

and you have in the setup file 
name='SimpleWebSocketServer'

and you are not using any namespaces. so I would go ahead and release this thing under the SimpleWebSocketServer name.

**Comment by kdschlosser** [comment]
It would be really nice to have this library on Pypi. one of the things you should also mention in some kind of description is it's usefulness in unittests. as an example with me. I have a library that uses a websocket client. in order for me to test I need to set up a websocket server to have the program connect to so my tests can run. right now I am doing some really hackish code to make it work. it would be a whole lot easier to run the tests if there was a light weight server that supported SSL.

**Comment by dpallot** [comment]
I've added it to PyPi as SimpleWebSocketServer.

**Comment by kdschlosser** [comment]
Oh sweet... thanks.

**Comment by davepallot** [comment]
I'll have a go at updating the documentation when I get a chance.

**Comment by mcepl** [comment]
> technically speaking the name of the library is SimpleWebSocketServer not simple_websocket_server.

Unfortunately, the package on PyPI is actually stored as

https://files.pythonhosted.org/packages/source/S/SimpleWebsocketServer/SimpleWebsocketServer-%{version}.tar.gz

(notice SimpleWebsocketServer != SimpleWebSocketServer)

**Comment by mcepl** [comment]
https://build.opensuse.org/package/show/devel:languages:python/python-SimpleWebSocketServer and working on getting it to the Factory.
